### ISSUE TITLE
Gcam is not working on my One Plus 3T

### ISSUE THREAD

**Issue by FazeelUsmani** [amirzaidi/gcam#10]
gcam is not working on my One Plus 3T after updating to Oreo

**Comment by FazeelUsmani** [comment]
Yeah, gcam is not working on my One Plus 3T after updating to Oreo and Oxygen OS 5.0

**Comment by amirzaidi** [comment]
Logcat?

**Comment by Saksey1** [comment]
Exactly the same issue with the 3 just saying

**Comment by derfrankie** [comment]
How can I send you and create the logcat - Oneplus 3T here

**Comment by cielantropi** [comment]
the logcat. @amirzaidi 

`FATAL EXCEPTION: main
                                                   Process: com.google.android.GoogleCamera:crash_report, PID: 27428
                                                   java.lang.SecurityException: Signature check failed for com.google.android.GoogleCamera
                                                       at android.os.Parcel.readException(Parcel.java:1942)
                                                       at android.os.Parcel.readException(Parcel.java:1888)
                                                       at gyd.a(Unknown Source:116)
                                                       at gwx.a(Unknown Source:50)
                                                       at gxb.run(Unknown Source:21)
                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                       at hca.run(Unknown Source:7)
                                                       at java.lang.Thread.run(Thread.java:764)`

**Comment by cielantropi** [comment]
also the app icon is the default android icon in oreo.

**Comment by amirzaidi** [comment]
That's not the right error message, that's the crash report send error

**Comment by Infiniteking21** [comment]
I'm also on op3t with Oreo same issue. Different weird logo and the AP crashes when launched, it works fine on my brothers 3t on 7.1.1

**Comment by amirzaidi** [comment]
What about other GCam versions? I'm using this on the open beta on 3T and it works fine

**Comment by amirzaidi** [comment]
Also, send me a full logcat please
